package com.myapp.DAO;

import com.myapp.model.*;
import com.myapp.model.Product;
import com.myapp.service.ProductService;
import com.myapp.service.ProductService;
import com.myapp.utils.DbPopulator;
import org.junit.*;
import org.junit.runner.RunWith;
import org.slf4j.bridge.SLF4JBridgeHandler;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

import java.math.BigDecimal;
import java.util.*;

import static java.lang.Boolean.TRUE;

@ContextConfiguration({
        "classpath:spring-app.xml",
        "classpath:spring-db.xml"
})
@RunWith(SpringJUnit4ClassRunner.class)
public class ProductServiceTest {

    static {
        SLF4JBridgeHandler.install();
    }

    @Autowired
    private DbPopulator dbPopulator;

    @Autowired
    private ProductService productService;

    private static boolean dataLoaded = false;

    @Before
    public void setUp() throws Exception {
        if(!dataLoaded) {
            dbPopulator.execute();
            dataLoaded = true;
        }
    }

    @After
    public void tearDown() throws Exception {
    }

    //------ProductDAO----------
    @Test
    public void testCRUDProduct() {
        //-----save------
        Brand brand = new Brand(201, "Mary Key", "Mary Key Description");
        List<Item> itemList = new ArrayList<>();
        itemList.add(new Item(0, new BigDecimal("12.09"), "Item Type", "Item Size", 11, 20, 5, "img02", 15.0, TRUE));
        Product productExp = new Product("Cream Save", brand, "img01", "description to product Cream", itemList, null);
        Product product = productService.saveProduct(productExp);
        int productId = product.getId();

        //-----getById-------
        Product productAct = productService.getProductById(productId);
        productExp.setId(productId);     //id is autogenerated
        productExp.getItemList().get(0).setId(product.getItemList().get(0).getId());     //id is autogenerated
        productExp.getItemList().get(0).setProductId(productId);     //id is autogenerated
        Assert.assertEquals(productExp, productAct);

        //-----update-----
        productExp.setName("Cream Update");
        productService.saveProduct(productExp);

        //-----getAll-----
        List<Product> productList = productService.getAllProducts();
        for (Product u: productList) {
            if(u.getId() == productId) {
                productAct = u;
                break;
            }
        }
        Assert.assertEquals(productExp, productAct);

        //-----delete-----
        boolean deleteResult = productService.deleteProductById(productId);
        Assert.assertTrue(deleteResult);
        Assert.assertNull(productService.getProductById(productId));
    }

    @Test
    public  void testGetProductByName() {
        Map<String, Object> param = new HashMap<>();
        param.put("name", "SoA");
        List<Product> productList = productService.getProductByParam(param);
        Assert.assertEquals("Soap", productList.get(0).getName());
    }

    @Test
    public void testGetProductByBrandId() {
        Map<String, Object> param = new HashMap<>();
        param.put("brandId", 201);
        List<Product> productList = productService.getProductByParam(param);
        Assert.assertEquals("Soap", productList.get(0).getName());
    }

    @Test
    public void testGetProductByPrice() {
        Map<String, Object> param = new HashMap<>();
        param.put("lowPrice", new BigDecimal(5));
        param.put("highPrice", new BigDecimal(40));
        List<Product> productList = productService.getProductByParam(param);
        Assert.assertEquals(2, productList.get(0).getItemList().size());
    }

    @Test
    public void testGetProductByCategoryId() {
        Map<String, Object> param = new HashMap<>();
        param.put("categoryId", 101);
        List<Product> productList = productService.getProductByParam(param);
        Assert.assertEquals(1, productList.size());
    }

    @Test
    public void testGetAllProductOrderBy() {
        Map<String, Object> param = new HashMap<>();
        param.put("orderBy", "name");
        List<Product> productList = productService.getAllProducts(param);
        Assert.assertEquals("Shampoo", productList.get(0).getName());
    }

    //-----CategoryDAO-----------
    @Test
    public void testCRUDCategory() {
        //-----save------
        Category categoryExp = new Category("Moisturizer", "Description");
        Category category = productService.saveCategory(categoryExp);
        int categoryId = category.getId();

        //-----getById-------
        Category categoryAct = productService.getCategoryById(categoryId);
        categoryExp.setId(categoryId);     //id is autogenerated
        Assert.assertEquals(categoryExp, categoryAct);

        //-----update-----
        categoryExp.setName("Creams");
        productService.saveCategory(categoryExp);

        //-----getAll-----
        List<Category> categoryList = productService.getAllCategories();
        for (Category c: categoryList) {
            if(c.getId() == categoryId) {
                categoryAct = c;
                break;
            }
        }
        Assert.assertEquals(categoryExp, categoryAct);

        //-----delete-----
        boolean deleteResult = productService.deleteCategoryById(categoryId);
        Assert.assertTrue(deleteResult);
        Assert.assertNull(productService.getCategoryById(categoryId));
    }

    @Test
    public void testGetCategoryByProductId() {
        //category_product (product_id, category_id) VALUES (100001, 101);
        List<Category> categoryList = productService.getCategoryByProductId(100001);
        Assert.assertEquals("Bath", categoryList.get(0).getName());
    }

    @Test
    public void testGetCategoryByName() {
        //category (name, description) VALUES ('Bath', 'Bath Description');
        List<Category> categoryList = productService.getCategoryByName("Bath");
        Assert.assertEquals("Bath", categoryList.get(0).getName());
    }

    //-----ItemDAO-----
    @Test
    public void testCRUDItem() {
        //-----save------
        Item itemExp = new Item(100002, new BigDecimal("16.35"), "Item Type", "Item Size", 11, 25, 14, "img02", 15.0, TRUE);
        Item item = productService.saveItem(itemExp);
        int itemId = item.getId();

        //-----getById-------
        Item itemAct = productService.getItemById(itemId);
        itemExp.setId(itemId);     //id is autogenerated
        Assert.assertEquals(itemExp, itemAct);

        //-----update-----
        itemExp.setQuantity(55);
        productService.saveItem(itemExp);

        //-----getAll-----
        List<Item> itemList = productService.getAllItems();
        for (Item c: itemList) {
            if(c.getId() == itemId) {
                itemAct = c;
                break;
            }
        }
        Assert.assertEquals(itemExp, itemAct);

        //-----delete-----
        boolean deleteResult = productService.deleteItemById(itemId);
        Assert.assertTrue(deleteResult);
        Assert.assertNull(productService.getItemById(itemId));
    }
}
